{{- if .Values.autoDeploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-upgrade-job-role"
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "statefulsets", "statefulsets/scale", "deployments", "deployments/scale"]
    verbs: ["get", "watch", "list", "patch", "update"]
{{- end }}
