{{- if .Values.autoDeploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-upgrade-job-rb"
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-upgrade-job-sa"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-upgrade-job-role"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
