{{- if .Values.twofactorauth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dast-twofactorauth.fullname" . }}
  labels:
    component: twofactorauth
    {{- include "dast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.twofactorauth.service.type }}
  ports:
    - port: {{ .Values.twofactorauth.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    component: twofactorauth
    {{- include "dast.selectorLabels" . | nindent 4 }}
{{- end }}
