{{- if .Values.twofactorauth.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dast-twofactorauth.fullname" . }}
  labels:
    component: twofactorauth
    {{- include "dast.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "dast-twofactorauth.fullname" . }}
  selector:
    matchLabels:
      component: twofactorauth
      {{- include "dast.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # This annotation makes sure that the pod is restarted on any upgrade
        # Restart is necessary as the secret used at env variable may have changed
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.twofactorauth.podAnnotations }}
        {{- toYaml .Values.twofactorauth.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        component: twofactorauth
        {{- include "dast.selectorLabels" . | nindent 8 }}
        {{- with .Values.twofactorauth.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.twofactorauth.podSecurityContext | nindent 8 }}
      containers:
        - name: twofactorauth
          securityContext:
            {{- toYaml .Values.twofactorauth.securityContext | nindent 12 }}
          image: "{{ .Values.images.twofactorauth.repository }}:{{ .Values.images.twofactorauth.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.twofactorauth.pullPolicy }}
          env:
            - name: FORTIFY_2FA_MASTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: two-factor-auth-master-token
            {{- with .Values.twofactorauth.additionalEnvironment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /rest/index.html
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /rest/index.html
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.twofactorauth.resources | nindent 12 }}
      nodeSelector:
      {{- with .Values.twofactorauth.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.twofactorauth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with .Values.twofactorauth.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
