apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dast-globalservice.fullname" . }}
  labels:
    component: globalservice
    # This component will be stopped before the upgrade job runs
    stopBeforeUpgrade: "1"
    {{- include "dast.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "dast-globalservice.fullname" . }}
  selector:
    matchLabels:
      component: globalservice
      # This component will be stopped before the upgrade job runs
      {{- include "dast.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # This annotation makes sure that the pod is restarted on any upgrade
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.globalservice.podAnnotations }}
        {{- toYaml .Values.api.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        component: globalservice
        # This component will be stopped before the upgrade job runs
        stopBeforeUpgrade: "1"
        {{- include "dast.selectorLabels" . | nindent 8 }}
        {{- with .Values.globalservice.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.globalservice.podSecurityContext | nindent 8 }}
      containers:
        - name: globalservice
          securityContext:
            {{- toYaml .Values.globalservice.securityContext | nindent 12 }}
          image: "{{ .Values.images.globalservice.repository }}:{{ .Values.images.globalservice.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.globalservice.pullPolicy }}
          env:
            - name: DBProvider
              value: {{ .Values.configuration.databaseSettings.databaseProvider }}
            - name: ConnectionStrings__DASTDB
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: db-connection-string
            - name: Logging__LogLevel__Default
              value: {{ .Values.logLevel }}
            {{- with .Values.globalservice.additionalEnvironment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.globalservice.resources | nindent 12 }}
      nodeSelector:
      {{- with .Values.globalservice.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.globalservice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with .Values.globalservice.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
