apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dast-api.fullname" . }}
  labels:
    component: api
    # This component will be stopped before the upgrade job runs
    stopBeforeUpgrade: "1"
    {{- include "dast.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "dast-api.fullname" . }}
  selector:
    matchLabels:
      component: api
      {{- include "dast.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # This annotation makes sure that the pod is restarted on any upgrade
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.api.podAnnotations }}
        {{- toYaml .Values.api.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        component: api
        # This component will be stopped before the upgrade job runs
        stopBeforeUpgrade: "1"
        {{- include "dast.selectorLabels" . | nindent 8 }}
        {{- with .Values.api.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          env:
            - name: DBProvider
              value: {{ .Values.configuration.databaseSettings.databaseProvider }}
            - name: ConnectionStrings__DASTDB
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: db-connection-string
            - name: ASPNETCORE_URLS
              value: 'http://+'
            - name: Logging__LogLevel__Default
              value: {{ .Values.logLevel }}
            {{- with .Values.api.additionalEnvironment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            failureThreshold: 6
            httpGet:
              path: /
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      nodeSelector:
      {{- with .Values.api.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with .Values.api.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
