apiVersion: v1
kind: Service
metadata:
  name: {{ include "dast-utilityservice.fullname" . }}
  labels:
    component: utilityservice
    {{- include "dast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.utilityservice.service.type }}
  ports:
    - port: {{ .Values.utilityservice.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: utilityservice
    {{- include "dast.selectorLabels" . | nindent 4 }}
