{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lim-secret.fullname" . }}
  labels:
    component: secret
    {{- include "lim.labels" . | nindent 4 }}
type: Opaque
data:
  lim-admin-password: {{ include "secrets.passwords.manage" (dict "secret" (include "lim-secret.fullname" .) "key" "lim-admin-password" "providedPassword" .Values.adminPassword "length" 16 "context" $ ) }}
{{- end }}