{{- if .Values.wise.enabled }}
# Cluster role for reading/listing pods (ClusterRoles are not namespaced)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dast-wise.fullname" . }}
  labels:
    component: wise
    {{- include "dast.labels" . | nindent 4 }}
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group /api/v1/
  resources: ["deployments", "replicasets", "pods", "endpoints"]
  verbs: ["get", "list"]
{{- end }}
