{{- if .Values.wise.enabled }}
# Service account to access pod's API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dast-wise.fullname" . }}
  labels:
    component: wise
    {{- include "dast.labels" . | nindent 4 }}
{{- end }}
