{{- if .Values.wise.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dast-wise.fullname" . }}
  labels:
    component: wise
    {{- include "dast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wise.service.type }}
  ports:
    - port: {{ .Values.wise.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.wise.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    component: wise
    {{- include "dast.selectorLabels" . | nindent 4 }}
{{- end }}
