{{- if .Values.wise.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dast-wise.fullname" . }}
spec:
  replicas: {{ .Values.wise.replicas.min }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      component: wise
      {{- include "dast.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # This annotation makes sure that the pod is restarted on any upgrade
        # Restart is necessary as the secret used at env variable may have changed
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.wise.podAnnotations }}
        {{- toYaml .Values.wise.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        component: wise
        {{- include "dast.selectorLabels" . | nindent 8 }}
        {{- with .Values.wise.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "dast-wise.fullname" . }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.wise.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.wise.securityContext | nindent 12 }}
          image: "{{ .Values.images.wise.repository }}:{{ .Values.images.wise.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.wise.pullPolicy }}
          env:
            - name: WISE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: wise-auth-token
            {{- with .Values.wise.additionalEnvironment }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 9442
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","/home/remote-pool/prestop.sh"]
          resources:
            {{- if .Values.wise.replicas.cpu.cores }}
              requests:
                cpu: {{ .Values.wise.replicas.cpu.cores }}
            {{- else -}}
            {{- toYaml .Values.wise.resources | nindent 12 }}
            {{- end }}
      nodeSelector:
      {{- with .Values.wise.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wise.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with .Values.wise.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
