{{- if .Values.wise.enabled }}
# Role binding to combine the wise-access-sa service account and role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dast-wise.fullname" . }}
  labels:
    component: wise
    {{- include "dast.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "dast-wise.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "dast-wise.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}