{{- if and .Values.wise.enabled .Values.wise.replicas.autoscale }}
# wise horizontal autoscaling:
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dast-wise.fullname" . }}
  labels:
    component: wise
    {{- include "dast.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.wise.replicas.max }}
  minReplicas: {{ .Values.wise.replicas.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dast-wise.fullname" . }}
  targetCPUUtilizationPercentage: 80
{{- end }}
